### ISSUE TITLE
Arduino Due compilation issue, __has_include() not available

### ISSUE THREAD

**Issue by NachtRaveVL** [davetcc/tcUnicodeHelper#3]
Unfortunately in Arduino Due the __has_include() functionality isn't supported, so there may have to be something done with manual setup defines to allow the library to understand what to include.

Without any proper handling, Print doesn't get included into the main class and out pops this on compilation:

```
In file included from C:\Users\hannah\Documents\Arduino\libraries\tcMenu\src\extras\DrawableDashboard.h:11:0,
from C:\Users\hannah\Documents\Arduino\libraries\tcMenu\src\extras\DrawableDashboard.cpp:2:
C:\Users\hannah\Documents\Arduino\libraries\tcUnicodeHelper\src/tcUnicodeHelper.h:354:12: error: 'size_t UnicodeFontHandler::write(uint8_t)' marked override, but does not override
size_t write(uint8_t data) override;
^
C:\Users\hannah\Documents\Arduino\libraries\tcMenu\src\extras\DrawableDashboard.cpp: In member function 'void DashMenuItem::paintTitle(tcgfx::DeviceDrawable*)':
C:\Users\hannah\Documents\Arduino\libraries\tcMenu\src\extras\DrawableDashboard.cpp:204:21: error: 'class UnicodeFontHandler' has no member named 'print'
unicodeHandler->print(titleText);
^
C:\Users\hannah\Documents\Arduino\libraries\tcMenu\src\extras\DrawableDashboard.cpp: In member function 'void DashMenuItem::paintItem(tcgfx::DeviceDrawable*)':
C:\Users\hannah\Documents\Arduino\libraries\tcMenu\src\extras\DrawableDashboard.cpp:227:21: error: 'class UnicodeFontHandler' has no member named 'print'
unicodeHandler->print(sz);
^
```

If you || defined(ARDUINO_SAM_DUE) on the __has_include() checks for the libraries you have you can get around this but looks like the solution may involve some fancy footwork. Good luck!

**Comment by davetcc** [comment]
There is an easy fix, for the print interface we can do that with the check for ARDUINO_SAM_DUE, for the various graphics libraries, I think that it is going to be user level, I've added:

TC_HARDWIRE_USING_U8G2 - when you want to use u8g2
TC_HARDWIRE_USING_ADAGFX - when you want to use Adafruit GFX
TC_HARDWIRE_USING_TFT_ESPI - when you want to use TFT_eSPI
TC_HARDWIRE_TCMENU_RENDER - when you want to use with TcMenu rendering.

I'll commit it later, but this is the quickest way around this, and a simple solution just requires a build flag to be added, if the user didn't have the capability to add build flags they could edit the header directly in the worst case.

**Comment by davetcc** [comment]
Actually I reopened this, the hasInclude support is too heavy, and it's a matter of time before it is unsupported somewhere else. It is too core to tcMenu to rely on a new feature. Given this is a fairly new library that's not reached 1.0 yet, I'm reimplementing it using separate headers that you bring in depending on the library in use.

For example for Adafruit_GFX it would change to (similar for all other cases):

    #include <tcUnicodeAdaGFX.h>
    UnicodeFontHandler handler(newAdafruitTextPipeline(gfxPtr), ENCMODE_UTF8);

**Comment by davetcc** [comment]
It will transparent to most tcMenu users, and a very simple change for anyone using the library elsewhere. One that brings maintainability benefits in the longer term
